Repository zeit/serve, pull requests merged in 2018-06, with the labels that each got.

#397 Added default `Content-Disposition` header
  package.json
  yarn.lock
Labels: minor

#403 Make `cleanUrls` stop stripping `.htm` extension
  package.json
  yarn.lock
Labels: major

#406 Support for `renderSingle` and reduced stat calls
  package.json
  yarn.lock
Labels: minor

#410 Correctly render hostname
  .gitignore
  bin/serve.js
Labels: patch

#412 Adding `-p` as an alias to `-l`
  bin/serve.js
Labels: patch

#415 Document usage with Now and update handler
  README.md
  package.json
  yarn.lock
Labels: patch

#416 Fixed requests to `/index` being redirected wrong
  package.json
  yarn.lock
Labels: patch

#419 Added error templates
  package.json
  yarn.lock
Labels: patch

#427 Reverted default port back to 5000
  bin/serve.js
Labels: major

#428 Allow dots in value of `public` option
  package.json
  yarn.lock
Labels: patch

#429 Brought back old message for serving
  bin/serve.js
  package.json
  yarn.lock
Labels: minor

#430 Added support for IPv6
  bin/serve.js
Labels: patch

#434 Read port from environment variable `PORT`
  bin/serve.js
Labels: minor
